- name: varibles from files
  hosts: local 
  connection: local # Ansible is connecting to local host
  vars_files:
  - course.yaml # these is the file where variables defined
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Course name is: {{ COURSE }}, trainer: {{ TRAINER }}, Duration: {{ DURATION }}"

