- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks: 
  - name: print the names
    ansible.builtin.package:
     name: {{ item }}
     state: latest
    loop:
    - {name: "nginx",state: "latest"}
    - {name: "mysql",state: "absent"}